### ISSUE TITLE
[FEAT] 캘린더 뷰 추가

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [Kyo-Pig/Mega-Pig#2]
### 문제 상황
- Monthly -> Daily까지로의 전환과정이 담긴 뷰의 부재
- 캘린더 뷰: TabBar의 좌측 가장자리에 해당하는 뷰

### 해결 방안
**MonthlyView 내부**
- 캘린더
- Summary

**DailyView 내부**
- 1주일에 해당하는 캘린더
- 영양소 그래프 (탄단지: 원형, 칼로리: 가로 막대형)
- 먹은 식단에 대한 사진 (정방형)

***ATTENTION***
1. MonthlyView <- Navigation Bar -> DailyView
-> Navigation Bar를 통한 Monthly : DailyView 이동
2. Monthly, DailyView 둘 다 TabBar 잔여

### TODO
:::MonthlyView 뼈대 작성:::
- [x] 상단 캘린더(월
- [x] 하단 Summary_데이터 연동 X
- [ ] 하단 Summary_데이터 연동 O

:::DailyView 뼈대 작성:::
- [x] 전반적인 Layout
- [x] 상단 캘린더(주)
- [x] 하단 그래프
- [x] 하단 사진 - CASE 사진의 수 >= 1
- [x] 하단 사진 - CASE 사진의 수 == 0

:::Connection:::
- [x] Monthly <-> Daily 연결
- [x] 사진 이미지 데이터 불러오기

### 비고 및 한계
*해당 이슈에서 해결하지 못한 사항들*
- 220407 - 220412: Date Picker 상에서 클릭된 날짜를 다시 클릭하는 경우 일일뷰로 넘어가지 못하는 한계
-> 220412 기준, 이 경우에 대해서는 Date Picker에게 .onTapGesture(count: 2)를 통해 일일뷰로 넘어가는 형태로 구현한 상태

---
> 진행 상황은 Comment로 아래에 달아주세요
ex) 220405: 00 추가

**Comment by jeong-hyeonHwang** [comment]
220407: 전반적인 계획 작성

**Comment by jeong-hyeonHwang** [comment]
**220408**
1. Calendar View 상단 캘린더, 하단 Summary 진행 중2. 
2. Test용 TabView 추가

### Summary에 들어가야하는 내용 일괄
- 000

**Comment by jeong-hyeonHwang** [comment]
**220409**
1. Daily View Layout 추가

### Daily View의 Photo 영역 구현방법
1. 완전 정방형: w == h
2. 상위 스택의 가로 세로 길이에 맞춰서 비율값으로
-> ex) 상위 스택 가로: x, 상위 스택 세로: y
--> Photo 영역 가로: x* 0.9, Photo 영역 세로: y*0.9

**Comment by jeong-hyeonHwang** [comment]
**220410**

1. Daily View 주(Week) 캘린더 추가
-> Button 형태로 구현

**Comment by jeong-hyeonHwang** [comment]
**220411**

**:::Daily View:::**
1. Pie Chart 구현
2. Bar Chart 구현
3. Photo Area 더미 데이터로 구현
4. Daily View의 전반적인 레이아웃 다듬기

**Comment by jeong-hyeonHwang** [comment]
**220412**

**:::Calendar View <-> Daily View:::**
1. 두 뷰 사이의 데이터 넘김에 있어서의 불일치를 @State, @Binding을 사용하여 해결

**:::Design:::**
1. 전반적인 컬러 값 수정
