### ISSUE TITLE
[FEAT] 식단 등록 뷰 레이아웃 구현

### ISSUE THREAD

**Issue by hanyeonhee** [Kyo-Pig/Mega-Pig#4]
### 문제 상황
- 카메라로 등록하는 뷰 생성 필요
- 등록 후 입력한 내용이 맞는 지 체크하는 뷰 생성 필요

### 해결 방안
- 뷰를 추가한다.
 
### TODO
- [ ] 카메라로 영수증 이미지 등록하는 뷰
- [ ] 카메라로 바코드 이미지 등록하는 뷰
- [ ] 이미지 등록 후 맞는 지 체크하는 뷰
- [ ] 검색해서 직접 추가하는 뷰
- [ ] 검색 뷰에 음식 추천 키워드 태그 추가

### 비고 및 한계
*해당 이슈에서 해결하지 못한 사항들*
- 탭 바는 누가, 언제 작업할 지 확인해야 함.

---
> 진행 상황은 Comment로 아래에 달아주세요
ex) 220407: SwiftUI View 추가
